### ISSUE TITLE
How to build development environment

### ISSUE THREAD

**Issue by howff** [ssec/polar2grid#145]
processmodis:/packages/cspp/polar2grid/develop/polar2grid> ./create_dev_env.sh /packages/cspp/polar2grid/develop/dist
Creating development environment directory: /packages/cspp/polar2grid/develop/dist
Answer yes (1) to all questions
Downloaded ShellB3 tarball to /packages/cspp/polar2grid/develop/dist/ShellB3-Linux-x86_64-20140212-r840-core-cspp.tar.gz
Will use this python executable for package installation: /packages/cspp/polar2grid/develop/dist/ShellB3/bin/python
Copying ms2gt to development bin directory (although only fornav gets copied)

Then I get this error:
Creating 'python' directory in development environment where python packages will be installed
./create_dev_env.sh: line 149: cd: /packages/cspp/polar2grid/develop/polar2grid/py: No such file or directory
Installing python packages in development mode
make: *** No rule to make target `all_dev'. Stop.
OOPS: Couldn't install python packages in development mode
FAILURE

**Comment by davidh-ssec** [comment]
Creating a development environment from that script is no longer supported. I reorganized the package to match what other python packages are doing. I will update the documentation soon.

Since I know you are familiar with satpy it may be best to follow the satpy installation instructions and then from that environment either install polar2grid from your checkout of the repository `pip install -e .` or if you want to install the latest development branch without editing code `pip install -U git+https://github.com/davidh-ssec/polar2grid.git@develop`. Note this is just off the top of my head so I'm sure there will be issues with some of the customizations that go in to the tarball. For example, you'll probably have to point `export PPP_CONFIG_DIR=/path/to/polar2grid/etc`. If you need to use the `crefl` reader you will also have to install those binaries separately. In the future the `crefl` correction will most likely be done in python and we won't need those binaries.

**Comment by djhoese** [comment]
From P2G 2.3 onward, these instructions can be used to build a development environment: https://github.com/ssec/polar2grid/blob/main/doc/source/dev_guide/dev_env.rst
