### ISSUE TITLE
Consider using inputs files as arguments as opposed to using -f <directories or files>

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#156]
This was suggested by Graeme.

**Comment by djhoese** [comment]
Talked with @graemely about this. I misunderstood the title for this but have talked to @rayg-ssec about this in the past. In summary, geo2grid currently does this:

```
geo2grid.sh ... -g mygrid1 mygrid2 mygrid3 -f /path/to/files/*.nc
```

The desired call would be to allow filenames to go on the end with no `-f` needed (make them positional arguments). The problem with that is that `-g` (and other flags) take a wildcard number of arguments so there is no way to distinguish something as a grid name versus a file path. The best long term solution would be to do:

```
geo2grid.sh ... -g mygrid1 -g mygrid2 -g mygrid3 /path/to/files*
```

Where any flag that can take an arbitrary number of arguments must have the flag specified multiple times. This is a big change for Geo2Grid (and Polar2Grid), but it probably best in the long run. Another suggestion I just remembered was from @rayg-ssec saying something like this might work:

```
geo2grid.sh ... -g mygrid1 mygrid2 mygrid3 -- /path/to/files*
```

I might be able to configure Geo2Grid to allow a combination of all three of these in the 1.1 release and then in the future we could move to the preferred long term solution (the 2nd one above). So what I'm saying is making all of these possible in one version:

```
geo2grid.sh ... -g mygrid1 mygrid2 mygrid3 -f /path/to/files/*.nc
geo2grid.sh ... -g mygrid1 -g mygrid2 -g mygrid3 -- /path/to/files*
geo2grid.sh ... -g mygrid1 mygrid2 mygrid3 -- /path/to/files*
geo2grid.sh ... -g mygrid1 -g mygrid2 -g mygrid3 -- /path/to/files*
```

The main question then becomes what version do we make the hard switch to the long term solution? Thoughts everyone?

**Comment by kathys** [comment]
I would prefer not to change this.  I believe that the less changes that users have to make to their current implementations, the more likely they will be to continue to use the software, and the less likely we are to upset their operational processing.

**Comment by djhoese** [comment]
It is important to note that we are working on Polar2Grid 3.0 in order to make it match Geo2Grid more closely since it is in general more flexible. So Polar2Grid's CLI will have to change regardless of the result of this issue. My suggestions above, specifically the `--` syntax (which is a standard/common bash calling pattern), was to avoid breaking other parameters like `-g` where users might expect to use `-g <grid1> <grid2> <grid3>`. @graemely I don't think passing files as arguments will ever be possible without the `--` because other flags will likely always take a wildcard number of arguments. For example `-p C01 C02 C014 C15` to specify what products you want to produce. With that flag taking any number of arguments and the command taking any number of files provided, there can be confusion from users when they do something like `geo2grid.sh ... -p C01 C02 /path/to/file1.nc /path/to/file2.nc` where geo2grid doesn't know what's a product and what's a file.

Thinking about it more, we want to make this easy for users who are writing scripts to call these tools. These users (Kathy and Liam) typically have variables like `G2G_GRIDS="usa1 usa2 usa3"` and then do `-g $G2G_GRIDS` when they call the command. Forcing users to do `-g <grid1> -g <grid2> -g <grid3>` would make this really difficult for most basic bash users. So maybe I add the support for the `geo2grid.sh ... -- /path/to/files*` while not changing anything else and keeping the `-f /path/to/files*`. As I mentioned, not having this `-- /path/to/files*` support was confusing to new users like @rayg-ssec when first using the tool. That's not something I want.

**Comment by graemely** [comment]
If continuing to support the `-g <grid1> <grid2> <grid3>` type syntax indefinitely is desirable then I agree that adding support for the `--` syntax is the most compatible and least confusing change for G2G users. I was not familiar with the `--` syntax but apparently it is part of POSIX, and it resolves the problem of unambiguously distinguishing between options and arguments, which seems to come up a lot.
