### ISSUE TITLE
Issues with overlaying active fires products using polar2grid 2.3.0a2 overlay.sh

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#205]
Trying to overlay active fire GeoTIFF image products onto a DNB GeoTIFF image from the 7 August 2019 test case.  Found a couple problems.

- [ ]  Trying to overlay "power" and "T4", "T13" onto dnb GeoTIFF results in large black rectangle in center of overpass image for both the IMG and MOD Resolution products.
Execution (from overlay_images test data directory):
overlay.sh ../sdr_images/j01_viirs_dynamic_dnb_20190807_105127_wgs84_fit.tif ../fire_images/noaa20_viirs_T4_20190807_105127_wgs84_fit.tif dnb_overlay_T4.tif

![DNB_T4_overlay_example](https://user-images.githubusercontent.com/1848019/63371856-7e91ee80-c34a-11e9-9be3-6fec9e9aafef.png)

- [ ] Overlaying the AFMOD confidence category resulted in small yellow rectangle in the middle of the image.  Execution (from overlay_images test data directory):
overlay.sh ../sdr_images/j01_viirs_dynamic_dnb_20190807_105127_wgs84_fit.tif ../fire_images/noaa20_viirs_confidence_pct_20190807_105127_wgs84_fit.tif dnb_overlay_confidence_pct.tif

![DNB_confidence_pct_overlay_exmaple](https://user-images.githubusercontent.com/1848019/63372075-02e47180-c34b-11e9-85b6-b98532940f50.png)

**Comment by kathys** [comment]
I should have mentioned that the IMG resolution confidence_cat overlay does seem to work properly.

**Comment by djhoese** [comment]
I don't think this will work for geotiffs that are on dynamic grids. I'm not exactly sure what this is happening, but can you try using the same data but on a static grid and see what the results are?

On second thought, I think the yellow rectangle is expected. Once #201 is merged and used then this would be a transparent background with yellow/orange/red fire pixels. The black rectangle is also expected since it is using the same rescaling as other IR bands. In P2G this defaults to 0 (black) being the fill value. You'd have to use the same strategy you've suggested in the past for specifying NODATA (to tell gdal_merge that 0 should be transparent). I could modify the overlay.sh script to detect this (if no Alpha band then assume 0 is fill).

**Comment by kathys** [comment]
The beta version tarball, polar2grid-swbundle-2.3.0b0.tar.gz, does not fix this problem.  The AFMOD images all show yellow boxes covering some portion of every pass.

**Comment by djhoese** [comment]
Can you post some screenshots @kathys ? Do all products show this?

**Comment by kathys** [comment]
See above.  They  look like that.  Yes, it is all AFMOD products that I try to overlay.
