### ISSUE TITLE
polar2grid-swbundle-2.3.0a2 - Output file creation ceases when processing multiple grids after first grid coverage is 0

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#209]
After implementing polar2grid tarball polar2grid-swbundle-2.3.0a2, my VIIRS USA grid GTIFF file creation started failing after the first grid that was found to have 0 percent coverage.  This behavior did not happen with the 2.3a1 version.  Previously, the software would print out an error message for a grid with 0 coverage, and then move onto the next grid.

I placed a set of test data here:

bumi:/data/users/kathys/test_data/viirs_grids

I executed the software from /data/users/kathys/test_data/viirs_grids/gtiff

Command:  
polar2grid.sh viirs gtiff -p dynamic_dnb --dnb-saturation-correction --grid-coverage=0 --grid-configs ../gridfile/usa_grids.conf -g usa1_250m usa2_250m usa3_250m usa4_250m usa5_250m usa6_250m usa7_250m usa8_250m -f ../sdr/GDNBO_npp_d20190822_t0657260_e0710119_b40505_c20190822071903911328_cspp_dev.h5 ../sdr/SVDNB_npp_d20190822_t0657260_e0710119_b40505_c20190822071912988125_cspp_dev.h5

The logfile is in the execution directory.  But I will also attach it.
[viirs2gtiff_20190822_065726.log](https://github.com/ssec/polar2grid/files/3531025/viirs2gtiff_20190822_065726.log)

**Comment by djhoese** [comment]
Looking at the code and the log, I don't think this is an a1 to a2 issue. I think this has been this way since switching to python 3 and it just never hit this data case (sounds odd to say it, but still). The issue seems to be in the change to get python 3 compatibility I switched the error/exception handling code for resampling from this:

```
try:
    # do resampling
except StandardError:
    # log that remapping failed
    # continue on to next grid
```

to:

```
try:
    # do resampling
except (ValueError, KeyError):
    # log that remapping failed
    # continue on to next grid
```

I must have also changed the error that gets raised in this swath usage case to be a `RuntimeError` (or maybe it was always that way). A `RuntimeError` is including in the `StandardError` "category", but is not a `ValueError` or `KeyError`. Mostly documenting this for myself.

Should be an easy enough fix (add `RuntimeError` to the except).

**Comment by kathys** [comment]
Pretty sure that I went from a1 to a2 on puff, but there is always the possibility that I managed to get this wrong .......

**Comment by djhoese** [comment]
This should be fixed by #208 (it was simple enough that I combined it with the RGB fixes).

**Comment by djhoese** [comment]
@kathys Have you had time to test this with the newest beta? Better?

**Comment by kathys** [comment]
Yes, and it works fine now.
