### ISSUE TITLE
Unable to create correct MERSI-2 natural_color image 

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#214]
When creating a MERS2 natural_color image using the polar2grid-swbundle-2.3.0b0.tar.gz tarball, the colors do not look right, and the clouds are not defined due to what looks like saturation. 

![Screen Shot 2019-10-15 at 2 28 09 PM](https://user-images.githubusercontent.com/1848019/66864608-2991e380-ef5b-11e9-9309-ee061a920941.png)

**Comment by djhoese** [comment]
For the record, I'll repeat what we said on slack about this: This is the first time we've had this RGB named "natural_color" in P2G (we have it in G2G). P2G uses a different scaling configuration so didn't have one for natural_color but has one for false_color. Since the configuration for natural color was missing P2G was defaulting to a dynamic linear stretching which is producing a not great image. Copying the false color for percentage reflectance data to use the name natural_color should fix this.
