### ISSUE TITLE
VIIRS L1B Reader Always Lists all bands available even when they are not!

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#254]
While Jenny Witt was doing testing on P2G for 2.3 release, she found that when you use the --list-products option on VIIRS L1B Moderate Resolution (MOD) files, it comes back with a list that includes all bands, even on nighttime files, where in reality, only includes bands 7-16.   As opposed to previous instruments like MODIS, the arrays do not contain Fill Values at night, they do not physically exist in the files, and therefore should not be listed as options for the users.

Two files are available here: bumi/data/users/kathys/test_data/viirs_l1b_jenny

One night and one day (0030 night dataset, 0242 daytime dataset)

**Comment by djhoese** [comment]
Mentioning this here for the record, this was brought up offline where my answer was:

This probably never worked since the Satpy viirs_l1b reader has no concept of checking availability based on file contents. This was never really a problem processing-wise since Polar2Grid is perfectly happy asking for "M06" and not getting anything back. Satpy's reader is currently only configured to say "M06 comes from the MOD file" and when you ask what is available it says "I have the MOD file therefore I can load the M06 product". The solution is in the Satpy reader to add the `available_datasets` method to the file handler so it checks that the configured dataset is actually in the file before claiming that the dataset is available for loading.
