### ISSUE TITLE
Lambert-Conformal mapping issues in add_coastlines.sh command within Geo2Grid package

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#267]
Hello, all --

1.)  We are wondering about the map lines being generated for the Lambert-conformal
projection we used in the Geo2grid  add_coastlines.sh  command.   Please see:

![GOES-16_ABI_RadC_cimss_true_color_2020079_170114Z_lc](https://user-images.githubusercontent.com/2246039/77342450-3252c680-6cfe-11ea-9f24-ecdfa00e6b68.png)

Note for example North Dakota, Kansas and the Oklahoma panhandle.   Something seems to be in error here.   One of our Python developers here at the University of Wisconsin thinks this might be a bug in the pycoast package.

2.)  We do have a reasonable workaround -- The Equirectangular Fit projection.  Here is a png file from the same case with that projection:

![GOES-16_ABI_RadC_cimss_true_color_2020079_170114Z_equirectangular](https://user-images.githubusercontent.com/2246039/77348780-0b00f700-6d08-11ea-8a51-a9aaa44ffb80.png)

3.)  You can find the output files for both #1 and #2 here:

[output_lambert-conformal_conus.txt](https://github.com/ssec/polar2grid/files/4370926/output_lambert-conformal_conus.txt)
[output_equirectangular_conus.txt](https://github.com/ssec/polar2grid/files/4371871/output_equirectangular_conus.txt)

4.)  We also generated CIMSS True Color imagery for the same date/time using GOES-16 ABI Full Disk (FD) and mesoscale sector M1 (RadM1) imagery.  The strange Lambert-conformal basemaps persisted:

![GOES-16_ABI_RadF_cimss_true_color_2020079_170018Z_lc](https://user-images.githubusercontent.com/2246039/77353029-3d155780-6d0e-11ea-8ab6-e142741d705f.png)
(https://github.com/ssec/polar2grid/files/4370934/output_equirectangular_conus.txt)
![GOES-16_ABI_RadM1_cimss_true_color_2020079_170025Z_lc](https://user-images.githubusercontent.com/2246039/77353079-51f1eb00-6d0e-11ea-9aae-0262a3d61031.png)

5.)  The following  two  GIF files were generated in McIDAS-X using GOES-16 imagery,
and show what that package thinks the Lambert-conformal projection & map should look like: 

![G16_LC_2020079_170114](https://user-images.githubusercontent.com/2246039/77342512-4bf40e00-6cfe-11ea-8be4-f7486b0f3d8e.GIF)
![G16_LC_2020079_170114_W_LL_LINES](https://user-images.githubusercontent.com/2246039/77342535-557d7600-6cfe-11ea-8f9d-e0c44351d000.GIF)

**Comment by djhoese** [comment]
Thanks for the issue @jpnIII. What if you play with the resolution/level of the borders in your `add_coastlines.sh` call? Does that change this behavior?

Side question: Your log files have things like `dashdashborders-resolution`, do you have a separate step that replaces `--` with the words `dashdash`? I was hoping to copy paste the commands you were using.

**Comment by djhoese** [comment]
If I remember correctly some of these issues were worked around by increasing the resolution of the overlays (I think this was mentioned in person or in a separate email thread). Otherwise, there have been many updates to pycoast trying to fix issues related to this (ex. lines going across the entire image, etc) and I'm hoping these changes will improve some of these results. Otherwise, if this is not an issue with pycoast it may be an issue with the coastline/border shapefiles that pycoast is using which we don't have much control over. I'm going to close this for now. If you (Jim) or anyone else notices these issues in G2G v1.1 then please comment here and we'll reopen it and dive deeper into the problem.
