### ISSUE TITLE
Questions about using the Geo2Grid add_coastlines.sh command colorbar option?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#277]
Greetings!   I had some questions about how to use the colorbar option within the Geo2Grid add_coastlines.sh command, in conjunction with GOES-16/17 ABI VISible and IR bands:
1.)   For  --colorbar-min      and     --colorbar-max  
       a.) For IR imagery,  should the min/max values be in terms of  radiance, brightness 
            temperature or 8-bit brightness?   Brightness temperature (K) would be ideal.   
       b.) For VIS imagery, should the min/max values be in terms of radiance, albedo or 8-bit 
            brightness?   Albedo would be ideal.

      FYI, the following are the units given in the ABI L1b NetCDF file metadata that I checked:
            ABI VIS bands:    W m-2 sr-1 um-1 
            ABI   IR bands:    mW m-2 sr-1 (cm-1)-1
2.) What should be specified for   --colorbar-units?   (depends on #1 above?)
3.) Does  --colorbar-units  determine what type of values need to be specified for  --colorbar-min and --colorbar-max?

**Comment by djhoese** [comment]
Hi Jim. I believe we've emailed about some of this before. You may want to check your email for a more detailed answer, but here's my answer for these particular questions:

1/2/3) The `-min`, `-max`, and `-units` are only controlling visually what is shown on the colorbar (if I remember correctly). So `-min` is the number that shows at the beginning of the colorbar, `-max` is the number that shows at the end of the colorbar, the rest of the numbers (ticks) on the colorbar will be determined linearly between these two points. The `-min` number is meant to reflect the real world unit for what the `0` 8-bit brightness values represents; `-max` is the 255 value. So for an IR channel scaled linearly between 180K and 330K (configuring in Geo2Grid enhancements), you would then specify `--colorbar-min 180 --colorbar-max 330`.

The `-units` is specifying the label that shows up in the center of the colorbar (I think) to show what units these numbers are in. So in the same example as above, to be accurate you would want to do `--colorbar-units K`. Since these are only visual elements there is no reason you couldn't convert the min/max to degrees C and then specify `--colorbar-units C` (or add the degrees symbol which I can't figure out how to do on my new laptop).

Hope that helps.

**Comment by jpnIII** [comment]
Thank you again, Dave.   This helps, and gets me closer to where I need to be.  ☺

Hope you and yours have a nice weekend!

Sincerely,

Jim
