### ISSUE TITLE
Use optionally provided pixel size from frontend in remapping

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#29]
@wstraka3 thought of the idea to use the data's native resolution in the remapping instead of needing it specified.  To implement this I would probably add an optional "pixel_size_x" and "pixel_size_y" to the frontend's produced meta data.  These will probably be nadir resolutions in most cases and are assumed to be in meters.

My initial thought is to still require the same number of parameters for dynamic PROJ.4 grids. You must specify either the grid size or the pixel size in the grid configuration.  Either way a command line option tells the remapping to override the pixel size of a dynamic grid's pixel size if the nadir parameters exist.  I doubt this will effect static PROJ.4 grids.  polar2grid already provides (or is planned to provide) a lot of flexibility to the user, we have to draw the line somewhere.

There is also the need to some how be able to tell if the projections units are in meters or not.  If they aren't then we obviously can't use the pixel_size parameters as the pixel size (ex. wgs84_fit is in radians).

**Comment by davidh-ssec** [comment]
I've made some progress in this situation. Mainly that if there are no defaults for resampling parameters check if the frontend told us the nadir and limb resolutions and use that to get a good guess.

Another feature that could be added came from some work with Ralph Kuehn. There could be a flag used in dynamic grids to use the center of the data for the center of the grid instead of the upper-left of the data as the upper-left of the grid. This shouldn't really make a difference if the dynamic grid has both origin and width/height unspecified. If only the origin is not specified then this makes a big difference.

This could also be expanded to provided the data's center lat/lon in the projection string. That has some chicken/egg complications in the "proper" way that this should be done.

**Comment by djhoese** [comment]
Polar2Grid 3.0 now depends on Satpy and uses `DynamicAreaDefinitions`. This logic could still be used/useful but hasn't been needed by anyone. The functionality would have to be added as part of the DynamicAreaDefinition in pyresample. That logic currently gets the entire lon/lat pair of the input data to "freeze" the dynamic area definition. There are also more tools in pyresample for creating your own area definitions from a center + radius kind of idea. Since this hasn't been needed/requested by anyone in Polar2Grid since 2015, I'm going to close this. Not a bad idea, just not going to implement it.
