### ISSUE TITLE
What's the actual difference between 2.4.1 on conda-forge and 2.3 on CSPP website?

### ISSUE THREAD

**Issue by yukaribbba** [ssec/polar2grid#307]
Except "Fix initial python packaging issues in order to create a conda-forge package"

**Comment by djhoese** [comment]
Good question. The conda-forge package (and the one on PyPI) was a rushed release so that Geo2Grid could be included on the GOES-R Beginner's Guide: https://www.goes-r.gov/downloads/resources/documents/Beginners_Guide_to_GOES-R_Series_Data.pdf

There are currently no intended feature changes between 2.3 and 2.4.1 except for some internal refactorings/rewritings which is why the release and commits are relatively cryptic. Note that this package is not functional for most Polar2Grid features; only Geo2Grid. We are working on a Polar2Grid 3.0 release which will address these issues and will result in a new CSPP tarball bundle release and a new `polar2grid` package released to PyPI and conda-forge.

Hopefully that clears up a little bit of the confusion than causes more confusion. If you have any other questions, feel free to ask here.

**Comment by yukaribbba** [comment]
Got it. 

So is there a schedule for 3.0 release? Any new features could we expect?

**Comment by djhoese** [comment]
The schedule is as soon as possible. We're pretty behind but hope to best testing the beta version in the next week or two. However, the features are mostly under-the-hood as we transition Polar2Grid to be more like Geo2Grid and depend on the Satpy library for almost everything. This should mean more multiprocess/threading friendly operations which should hopefully mean better memory usage and hopefully faster run times. Overall it should mean more flexibility in the future. It is a little early here so I'm having trouble thinking of what else is new right now.

**Comment by yukaribbba** [comment]
Yeah we do need batch processing. And is it possible to make EWA easier to use? For example, just let the program determine 'fornav D' and 'fornav d', depending on the instrument types. I'm still confused about these two.

**Comment by djhoese** [comment]
Yes, that is actually what #305 is about. However, this has always had defaults configured in the readers so I wouldn't think you would need to specify this yourself. What cases have you had where you've needed to do this?

Also, I've rewritten the EWA resampling in the pyresample library to try to use dask more. This should hopefully reduce memory usage on large VIIRS and MODIS passes but we haven't thoroughly tested it yet.

**Comment by yukaribbba** [comment]
Oh! Looks like I misunderstood the guide. I thougth I need to specify theme manually. Thanks!

**Comment by djhoese** [comment]
Which guide?

They are options if you want to control them yourself, but they should have sensible defaults. Oh! Except in the case of the `crefl` reader as that supports two different sensors you do have to specify the flags for MODIS I think.

**Comment by djhoese** [comment]
I think the original question here was answered (even if it isn't a great answer). I'm going to close this. If you have further questions please create a new separate issue. Thanks.
