### ISSUE TITLE
A few more geo2grid.sh questions

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#351]
Greetings, all -- We have come across some more geo2grid.sh-related items that we don't understand.   In general, we know that new ABI products should be defined in  composites/abi.yaml.   Furthermore, any enhancement(s) that need to be applied to the new products should be stored in  enhancements/abi.yaml.   With this in mind:

1.)  What is the purpose of enhancements/generic.yaml ?  Is this for products that do not fit nicely into enhancements/abi.yaml?
2.)  There is a little confusion about what calibration/units is being used within products defined in composites/abi.yaml.  For example, we are assuming that if a prerequisite is any of C07 -> C16, that the imagery pixel values being dealt with will be brightness temperature in Kelvin.  Or, if a prerequisite is any of C01 -> C06, then the imagery pixel values will be in terms of albedo, ranging from 0.0 -> 100.0   It also looks like one can override the default units by specifying  "units: ..."    Does this sound correct?   
3.)  We were trying to work with gammas.   Even though we tried to change gamma value(s), we were not seeing any effects in the output imagery.   I have included below the product entries we were trying to use.   FYI, we tried storing the kwargs: gamma values both as a list [] and set {} -- no difference seen.  When we ran in debugging mode (-v), there was no information listed concerning the gamma values being used.  Any idea(s) what we are doing wrong here?

Thank you again for your help with this!

Sincerely,

Jim
1.)  Entry contained within composites/abi.yaml

plume_diff_night:
    description: >
      Plume RGB, for GOESR: NASA, NOAA
#   references:
#     None.
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
      - name: C07 
      - name: C05 
      - compositor: !!python/name:satpy.composites.DifferenceCompositor
        prerequisites:
          - name: C08 
          - name: C10 

2.)  Entry contained within enhancements/abi.yaml
#CIMSS Geo2Grid generic product enhancements (${GEO2GRID_HOME}/etc/satpy/enhancements/generic.yaml) added by: Tim Schmit, Jim Nelson
# version for viewing rocket plumes : C07, C05, C08 (diff), best for nighttime use (was 0 to 30 K)

  plume_diff_night_default:
    standard_name: plume_diff_night
    operations:
    - name: stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs:
        stretch: crude
        min_stretch: [290,  0, 10]
        max_stretch: [330, 50, 30]
    - name: gamma
      method: !!python/name:satpy.enhancements.gamma
      kwargs:
        gamma: {0.7, 1.0, 1.7}

**Comment by djhoese** [comment]
Hi Jim,

1. `enhancements/generic.yaml` is for *shared* (read: "generic") enhancements. That is, enhancements that could be shared by more than one sensor's products. For example, scaling all brightness temperatures, all reflectances, all brightness temperatures with a single set of defaults enhancements in `generic.yaml` would be easier than defining it for each sensor (abi, ahi, viirs, etc).
2. The `units` that can be defined in the enhancements config is to say "this enhancement is applied to data **with** these units". It doesn't change (at least right now) how the data is handled in that enhancement. A use case might be knowing that one rain rate product from a reader is in millimeter (`units: mm`) and another reader produces a rain rate in centimeters (`units: cm`). Using `units` in two enhancement configuration sections would let Satpy know that "this enhancement should be applied to data with these units and this enhancement when the data has these units".
3. Is that the full section for your composite configuration? What's the name of it? My guess is you named it `plume_diff_night` but you don't include a `standard_name: plume_diff_night` in the composite config. If you did then `standard_name` would be included as metadata alongside the produced composite. Then `standard_name` could be used, as you have it, in your enhancement config. `standard_name: plume_diff_night` in your *enhancement* config is saying "use this enhancement when the standard_name metadata for a dataset equals 'plume_diff_night'". An alternative option is to change your enhancement to say `name: plume_diff_night` instead of `standard_name`.

**Comment by jpnIII** [comment]
Hello, Dave – Thank you for your (as always) quick and thorough replies!

Please see my enclosed replies in red.

Sincerely,

Jim

**Comment by djhoese** [comment]
FYI your replies go through github so none of the formatting is preserved, but I think I figured out what parts you added. Regarding the plume_diff_night: I'll call "channel_8_default" the "section title". It is simply an identifier for an enhancement configuration section and doesn't actually control anything **except** to distinguish itself from other enhancement sections. So you can't have two enhancement sections named the same thing because one would override the other (if you're familiar with java or python they are keys in a hashmap/dictionary).

Composites on the other hand the "section title" is the actual name of the composite that is going to be generated. So in a composite config you have:

```
<composite_name>:
    compositor: ...
    prerequisites:
        - ...
        - ...
        - ...
    <other metadata>
```

The `other metadata` can include things like `standard_name: "<some string value>"` or whatever else you want.

Now for enhancements we have:

```
<section title>:
    <identifying metadata>
    operations:
        - ...
        - ...
```

Where `identifying metadata` can be things like `name`, or `units`, or `standard_name`, or `sensor`, etc. The enhancement section that is used in the end to scale the product is the one that has the most matches (with some priorities for things like `name` and `sensor`). So in the section you put above with `name: C08`, that enhancement will only be used for products with the exact name "C08" (remember "channel_8_default" doesn't actually mean anything). You'll also see enhancements with things like `standard_name: "true_color"`. This means this will be applied to any products that have a standard_name (remember, this is "other metadata" from the composite) equal to `true_color`. Using things like standard_name for enhancement matching mean you can have one enhancement section that applies to many products.

I hope this clears some things up, but let me know if there's anything else.

**Comment by jpnIII** [comment]
Thank you, Dave -- This does help us out.   Take care!
