### ISSUE TITLE
A general question on best practices for running Geo2Grid

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#387]
Hi all -- I run Geo2Grid via shell script(s).    If I have a range of days/times to process, and  N  products to process for each discrete day/time, then I can see processing my data in either of the following ways.   Which way is better overall?

1.)  Loop through all the days/times (the outer loop, if you will).   For each discrete day/time, process each of the N parameters.  This approach has the advantage that one can specify all  N  parameters on the geo2grid.sh commandline, so you can generate all parameters simultaneously for each discreet day/time -- no looping through parameters required, per se.
2.)  Loop through each of the N parameters.  For each parameter, loop through all of the days/times.

I seem to recall that there is some innate advantage somewhere in the "bowels" of Geo2Grid  to generating all products simultaneously (can't remember what it is, though).   Perhaps something about Geo2Grid knowing which data it has to work with at a given day/time, and therefore knowing which parameters it can or cannot compute?

At any rate, I think that approach #1 is better, but I wanted to check with the experts.  

Thank you for your advice!

Sincerely,

Jim

**Comment by djhoese** [comment]
Assuming no system limits (ex. running out of memory while processing) I would go with option 1. You are correct that Satpy (used by Geo2Grid) will attempt to share or reuse any products that are shared between different products. Additionally there are different types of caching for things like resampling that are better when they don't have to be loaded from disk over and over again. There are also even optimizations in lower-level libraries like dask which Satpy uses where it will try to be smart about what data it holds in memory between operations and do operations/processing in a different order if it thinks that things will perform better (faster, less memory).

So option 1, but if the machine doing the processing is running out of memory or is loading or saving data from a slow disk (network storage) then maybe it would be smart to only run a couple products at a time. But even in these cases there are ways to improve this just by tweaking settings in Geo2Grid (make sure geotiffs are compressed and tiled, modifying number of parallel workers, etc). If you are going to run a few products at a time then I would suggest selecting groups of products to run in each execution instead of a single product at a time and choose the group based on what input bands are being used (ex. process true_color and all of its dependency bands in the same call).

**Comment by jpnIII** [comment]
Hi Dave -- Thank you again for your (as always) fine and timely response!

It is a pleasure working with you.

Sincerely,

Jim

**Comment by djhoese** [comment]
Not really. Sometimes it is documented. Sometimes the composites come from Satpy and may or may not be documented. Sometimes composites depend on other composites or have "corrections" (ex. rayleigh) applied to them that depend on other input bands or composites. So there isn't really an easy way to just *know* the dependencies beyond looking at the various YAML files and tracking down what is loaded. One thing you could do is check the `.log` file generated by Geo2Grid and look for DEBUG messages with something like "Unloading dataset X because it is no longer needed". These messages should appear for inputs to composites.

**Comment by jpnIII** [comment]
Very good, Dave – Thank you!

Sincerely,

Jim
