### ISSUE TITLE
Confirm ewa and options are working correctly in v3.0

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#440]
Please confirm that the EWA resampling method and options are working correctly.  I have tried using the --method ewa option along with --maximum-weight-mode and --weight-delta-max, --weight-distance-max and I cannot see the effects that I expect when using them.

**Comment by kathys** [comment]
This has become more important as Liam would like me to use this for ROFFS chlor products for MODIS.

**Comment by djhoese** [comment]
I'm working on adding tests for all the possible cases, but wanted to document them here too so we can discuss them before I get too far along and to make sure there are no surprises:

1. No `--method` provided and no resampling options provided (default)
   a. Polar2Grid: Look up default resampler and options from resampling.yaml config. For swath products this is "nearest" resampler with no additional customization unless otherwise configured (ex. VIIRS has a specific custom configuration). Default grid is wgs84_fit.
   b. Geo2Grid: Look up default resampler and options from resampling.yaml config. For gridded products (ex. geostationary ABI/AHI) this defaults to "native" for "native grids" (MAX, MIN, or a custom grid that is a factor of the native projection). If the provided grid from the user is not native, then "nearest" resampler is used with no additional options. Default grid if not customized by user is "MAX".
2. No `--method` provided but one or more resampling options provided. Default resampler and options are searched for in resampling.yaml. Options provided by user are added on to default options. This is currently not working.
3. `--method` provided but no options provided by user. Resampling config is *NOT* searched and options default to algorithm code defaults.
4. `--method` provided and options customized by user. Resampling config is *NOT* searched, options default to algorithm code defaults but user provided options are also provided. I think this is also not working and is what your original description here is describing.
