### ISSUE TITLE
netcdf or hdf writer

### ISSUE THREAD

**Issue by joleenf** [ssec/polar2grid#471]
I am thinking I just missed an issue request already open for this.  Are there plans to facilitate netcdf or hdf writing of files with geo2grid?  Currently planning on using satpy unless there is a geo2grid work around.

**Comment by djhoese** [comment]
So there is the `hdf5` writer, but this is mainly meant for backwards compatibility with older Polar2Grid versions. It is not in Satpy and only available in P2G/G2G.

Technically the `cf` writer should be usable right now, but since it isn't configured/added in P2G/G2G you won't be able to customize any of the parameters. I'm not against added it.

**Comment by joleenf** [comment]
Hi Dave,

"cf" is not recognized as a known writer argument.  That writer is in satpy, would some sort of interface in polar2grid needs to be written in order for that to work?

**Comment by djhoese** [comment]
Darn. I had hoped that G2G/P2G would let you pass any satpy writer and it would "just work". So in this case, yes, a wrapper would need to be written similar to the geotiff writer. We could maybe update P2G/G2G to allow any random writer that exists in Satpy, but in this case you'll want to add command line options to map to kwargs in the satpy writer anyway.

**Comment by djhoese** [comment]
I think this is close-able now that #476 was merged a long time ago. Let me know if we need to reopen it. Or we can create a new issue.
