### ISSUE TITLE
Evaluate SSE4A instructions and more optimizations for ms2gt static builds

### ISSUE THREAD

**Issue by rayg-ssec** [ssec/polar2grid#48]
The static builds of ms2gt are x86-64 with baseline SSE instruction set and optimizations, which should be available everywhere.

Building with -msse4a and -O2 or -O3 compiler flags should be benchmarked at some point to see if it provides a significant performance boost without severe limitation to what machines can be used (i.e. anything recent enough to be useful for CSPP).

**Comment by davidh-ssec** [comment]
I have rewritten fornav as a python extension that includes many logic optimizations. I include the `-O3` by default which seemed to help when I was doing initial modifications to the ms2gt version. There are multiple optimizations that can still be done, but I should really remove the cython requirement for the fornav extension (ll2cr still needs cython). The logic is fairly simple so that it can be entirely kept in one C++ file. I can also pull out one of the if statements in to 2 separate functions. The `-msse4a` option would be another optimization along with some OpenMP or OpenCL in the future, but probably not until v2.1.

**Comment by djhoese** [comment]
I've been looking at this more and more and given that the ms2gt code now comes from pyresample which has a goal of building for multiple platforms (not just a single ShellB3 Polar2Grid tarball), I'm worried about adding this. Although most modern CPUs can probably handle this and probably even newer options, it complicates the maintenance of the packages which I'm nervous about.

I haven't done this in the 9 years since this was created and I just don't think it is going to happen. If I get bored maybe I will try one quick test running it on my machine with some of these flags and see what happens.

**Comment by djhoese** [comment]
Ok so just did a simple profiling run with satpy modis_l1b using the dask-friendly version of EWA with and without the `-msse4` compile flag. I did not change the code at all and didn't actually look if the binary `.so` output changed. Regardless there was no performance difference and looking at the graphs I'm not sure fornav (the part of ms2gt that would benefit from these instructions) actually takes very long compared to other parts of the processing and moving things around. Especially now that things are split across dask workers.

I'm going to close this for now. There are probably some enhancements that could be made, but I think they are on the python side in the areas that are rearranging dask chunks to go from input chunks to resampled output chunks.
