### ISSUE TITLE
For GOES-ABI band 7, stretching (8-bit) brightness range between 270K <-> 290K ?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#488]
Hello, all --  I guess that the following request/question is kind of an extension of issue #278.   I cut/pasted #278 below.

We have a situation with the new GOES-18 satellite where we are seeing essentially N/S noise striations in ABI band 7 (3.9um).   To try to "draw out"/emphasize these artifacts, we thought it might be useful to stretch the band 7 imagery between a range of, say, 270K <-> 290K.   I believe that the current geo2grid GOES-ABI band 7 conversion between brightness temperature and (8-bit) brightness is a bi-linear stretch, where 163K->242K is one linear scale, and 242K->330K is a different linear scale.   Together, the two linear scales map band 7 brightness temperatures between 163->330K to 8-bit brightnesses ranging from 0 -> 255.

We would like to be able to, for example, map 270K -> 290K (range=20K) into an 8-bit brightness range of 180 -> 220 (range=40 counts).  In this way, every brightness count change of 1 count would represent a brightness temperature change of 0.5K.

I think that perhaps we might be able to do what we want by creating an entry within  satpy/enhancements/abi.yaml, but are unsure of how to proceed.   Do you have any advice for us?

Thank you for your ongoing help!

Sincerely,

Jim
--------------------------------------------------------------------------------------------------------------------------------------------------
**Issue #278:**

Hello, all -- This is a request to enhance the brightness temperature <--> 8-bit brightness conversion used for GOES-16-19 ABI band 7, the 3.9um band. This band is strongly affected during daylight hours by reflected solar energy, and is also sensitive to energy emitted by fires on the earth's surface. The brightness temperatures sensed in this band can far exceed the maximum value currently allowed in the Geo2Grid software -- 330K. Our request/hope would be an update to make Geo2Grid do what is currently done by McIDAS-X for this band:

        INPUT(K)      OUTPUT(8-bit brightness value)
        ----------      ----------------------------------
            190                               255
            242                               190
            330                                 14
            400                                   0
There are three(3) segments in this "stretching table" employed by McIDAS-X:
190-242, 242-330, 330-400. Brightness temperatures <--> 8-bit brightnesses that fall within a given segment are determined by linear interpolation. For example, 216K would be assigned a brightness of 223 (I think that 222.5 would get returned as 223), and 390K would be assigned a brightness of 2. See the following McIDAS-X documentation for further information:
https://www.ssec.wisc.edu/mcidas/software/x/info/mcstretch_info/#details

Thank you for your considerations!

**Comment by djhoese** [comment]
Is there a reason you changed `name` to `standard_name`? If you only want this new enhancement to apply to C07 then you should have `name: C07`. The first usage of c07_linear is fine.

**Comment by djhoese** [comment]
Oh and you should be requesting C07. You are configuring a new default scaling for C07, not a new product based on C07.

**Comment by djhoese** [comment]
These YAML files are not technically something the user is supposed to touch. I have only helped users who request more details on them because the files and functionality is there. Modifying YAML files is considered an advanced feature and is definitely not a supported feature for the 1.0.x Geo2Grid releases. I can't say for sure what our plan will be for the next release as far as advertised support.

Your YAML, in the most basic method, should have this:

```
C07_linear:
    name: C07
    operations:
      - name: linear
        method: !!python/name:satpy.enhancements.stretch
        kwargs: {stretch: 'crude', min_stretch: 330., max_stretch: 180.}
```

This overrides the default enhancement for C07. The only way to make "extra" versions of a single channel is to essentially make a new "composite" in order to give the channel a new name. So this would require changes in `etc/composites/abi.yaml` for the new composite (let me know if this is what you want and I can put some notes together). Then once you have that composite, which would have its own unique name, then you could make a custom enhancement in `etc/enhancements/abi.yaml` for that specific composite.

The use of `standard_name:` is to allow an enhancement to be "generic" where you might have multiple datasets with the same standard name. For example, `toa_bidirectional_reflectance` products could all be scaled the same because they are all reflectances. Their "name" may be different, but their "standard_name" should be equal in most cases. In this way, "standard_name" is similar to the CF definition of the term although Satpy/G2G do not always strictly follow CF naming schemes for standard_name. When you know you want the enhancement to apply to a specific channel/product then using `name:` is recommended.

**Comment by djhoese** [comment]
If I remember correctly the original purpose of this issue/question has been resolved. Closing...

**Comment by jpnIII** [comment]
Thank you again, Dave.

Sincerely,

Jim
