### ISSUE TITLE
Enabling the display of GOES radiances within Geo2Grid?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#490]
Greetings, all -- Has there been any thought of adding the capability to display GOES radiances to Geo2Grid?   There might be situations where the ability to display this type of data (to complement the current display of brightness temperatures) could be useful.   It would be sort of like "peeling off another layer of the onion" -- displaying information directly from the L1b radiance files versus displaying data that has been converted to brightness temperature.   Thank you again!

**Comment by djhoese** [comment]
Additional use cases weren't really described here. I'm hesitant to add these extra radiances due to how much they clutter the already long list of available products and composites. In my experience, people end up wanting to look at radiances when they're doing lower-level analysis with "the numbers". I'm not sure that type of analysis is served well by using Geo2Grid and Polar2Grid which are typically more focused on making a "pretty picture".

I'm willing to open this back up after a discussion with @kathys and with more use cases described by you Jim, but for now to just clear out these old issues I'm going to close this.

**Comment by jpnIII** [comment]
Thank you, Dave.

Take care.

Sincerely,

Jim

**Comment by jpnIII** [comment]
Hello, Dave – we on 2nd floor will have to re-examine some of these earlier Geo2Grid requests upon release of 1.2 and see where things stand at that time.

Later.

Sincerely,

Jim
