### ISSUE TITLE
MiRS AWIPS NetCDF attributes differ from P2G V2.3

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#510]
P2G V3.0 MiRS AWIPS NetCDF file products have vastly different `physical_element` names than previous versions of P2G and therefore are not recognized in our local AWIPS implementations.  For example, the previous `physical_element` name of the rain rate product was `rain_rate`, while in Version 3.0 it is `RR`.  Since these products are being used by NWS in Alaska and Guam, the attributes need to stay the same.

**Comment by djhoese** [comment]
This *should* hopefully be fixed by the renaming/aliasing of the MiRS product names mentioned in #508. I'll make sure to test this aspect of it. Hopefully the aliasing fixes it or it might get a little unfun to fix.

**Comment by djhoese** [comment]
As discussed in the meeting today, MiRS is configured properly in the P2G-specific awips_tiled.yaml:

https://github.com/ssec/polar2grid/blob/2ef9be9b7814d679ba0d2ad86f225454c86e6831/etc/writers/awips_tiled.yaml#L662-L669

However, because the product names are wrong in the reader, the configuration section in the YAML file is not properly found/used. Based on the above config, fixing the reader name products should fix this.

Best case aliasing in the reader will just *work*. Worst case I need to make duplicate entries in the reader (in a P2G-specific reader YAML) that point to the same variables that already exist in the Satpy YAML. Not a huge deal either way.

**Comment by djhoese** [comment]
```
(polar2grid_py310) davidh@janet:/tmp$ ncdump -h SSEC_AII_noaa18_amsu-mhs_btemp_23v_LCC_T001_20180914_1607.nc | grep physical_element
                data :physical_element = "MIRS 23 GHZ V" ;
                :physical_element = "MIRS 23 GHZ V" ;
(polar2grid_py310) davidh@janet:/tmp$ ncdump -h SSEC_AII_noaa18_amsu-mhs_clw_LCC_T001_20180914_1607.nc | grep physical_element
                data :physical_element = "MIRS CLW" ;
                :physical_element = "MIRS CLW" ;
```

Looks like I've got the fix.
