### ISSUE TITLE
Binary writer argument list incorrectly includes `--fill-value` option

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#537]
The CSPP Polar2Grid Documentation includes `--fill-value` which was probably taken from the geotiff writer argument list, since the description is "Instead of an alpha channel fill invalid values with this value. Turns LA or RGBA images in to L or RGB images respectively."

**Comment by djhoese** [comment]
So I've reviewed the old binary writer and the new one and I think this flag should exist. As decribed in #335 where I added this satpy-compatible version of the binary writer I noted a slight change in behavior. The old writer would decide to enhance (rescale) things only if the data type of the output file was different than the data being saved (ex. saving uint16 data to a uint8 binary file). It also never enhanced floating point data for some reason. The new version of the writer defaults to always applying enhancements to be more consistent. This may require some users who want the unenhanced data to specify `--no-enhance` on the command line, but is more consistent with the other writers (ex. geotiff) where enhancement is done by default. I would understand changing this default for the binary writer.

As for the fill value, there was actually always a `fill_value` keyword argument in the old writer so if you wanted to save a binary file with a fill value of 0 instead of NaN you could...but it never got its own command line flag to use it. The new version of the writer fixes this. I'll make a PR to fix the description of the flag.

@kathys thoughts?

**Comment by kathys** [comment]
I am working on the writer portion of the P2G V3.0 doc, and I think you describe the enhancement part pretty well in the binary writer section.  I think it will be fine after the PR.
