### ISSUE TITLE
"Fog" product being created during the day for VIIRS

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#544]
Using the P2G Version 3.0 tarball `polar2grid-swbundle-20221013-222816.tar.gz`, I created all default products for an entirely day set of granules from VIIRS, and it created the ifog product as part of that suite.

The log file is here:  `bumi:/data/users/kathys/version_3_0_timing/output_viirs_rc1_v_3_0/viirs_sdr_geotiff_20220718_191730.log`

There is a related closed issue for MODIS: https://github.com/ssec/polar2grid/issues/421

**Comment by djhoese** [comment]
Hhhmm interesting. This doesn't seem to happen for me with my own test case. Looks like it'll need more than an initial basic testing.

**Comment by djhoese** [comment]
Ok I've played with this tonight and I think I have a fix. If I have time between meetings tomorrow I'll try to make a pull request. Here's the idea...

For a usual composite like true_color that requires resampling to be generated:

1. Open files and load requested products and products needed to generate composites like true_color.
2. Attempt to generate composites and remove any products that aren't needed. For example, you want to load true_color but no longer want/need the bands that were used as input so unload them. Anything that is requested, whether it was generated right now or needs resampling is added to a "wishlist".
3. Do day/night filtering of what is currently loaded. Remove products that do not meet the day/night thresholds.
4. Resample whatever is left after filtering.
5. Try generating any remaining composites.

Now, for `ifog`, we have the same set of operations *except* in step 2 it was actually able to be generated. In step 3 we remove the `ifog` product because there isn't enough day, but we *don't* remove `I05` and `I04` that were used to generate it. The **bug** is in step 2 where our wishlist wasn't modified and it still includes `ifog`. So after resampling we see `ifog` in the wishlist and we see `I05` and `I04` in our loaded datasets, so Satpy regenerates `ifog`.
