### ISSUE TITLE
Using `--extra-config-path` pointing to user defined rescale yaml file does not work

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#546]
I have been trying to rescale an ACSPO SST dataset for the P2G V3.0 example section but cannot get the polar2grid.sh execution to apply it.  I am trying to use this method `--extra-config-path $PWD/my_rescale.yaml`.  I can see from the log file that it identifies my file, and adds it to the /tmp directory, but it never actually uses the values that I have in the file.

I did verify the the original way of doing this still works - enhancements/generic.yaml.

The log file and data are here: `bumi:/data/users/kathys/test_data/acspo/example_for_documentation/oct_3_tarball_examples`

**Comment by djhoese** [comment]
Did a quick check and this was a simple bug to fix. I just need to make sure my tests capture the mistake. Basically I made it so Polar2Grid's paths are applied after the users custom paths. Since Polar2Grid has an enhancement matching yours (match against the same standard_name) the Polar2Grid builtin enhancement took priority over your custom one.

Swapping the order that the extra config paths are applied internally should fix this.
