### ISSUE TITLE
Degradation in VIIRS true color image sharpness

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#558]
Using the new October 25 tarball, I was working on putting together the verification tarball for the P2G V3.0 release.  When I compared the output VIIRS GeoTIFFs to the original P2G 2.3 versions, there is a definite degradation in the sharpness of the image (Miami).  I am attaching them below.  The July 18 tarball did not have this degration.

data is here:  `bumi:/data/users/kathys/test_data/modis/doc_exmples/input/polar2grid_test/viirs`

V2.3
![Image](https://user-images.githubusercontent.com/1848019/199842370-5531e25c-8809-439b-9aa3-cbd75d0cac90.png)

V3.0
![Image](https://user-images.githubusercontent.com/1848019/199842480-68487577-2b10-447a-8f04-1a3c842a2be5.png)

**Comment by djhoese** [comment]
This is the difference between `--weight-distance-max 1.0` (the sharper image) and `--weight-distance-max 2.0` (the new default). If you check your logs, you actually specified this flag for the `work_jul18` tarball with `--weight-distance-max 1`. In fact, if I use the July tarball and the two October tarballs I get the same result (the less sharp one).

As a reminder, this flag is needed at `2.0` otherwise we started seeing holes in higher latitudes.

**Comment by djhoese** [comment]
@kathys if you want to talk more about this we can, but otherwise I'm not sure there is anything to do here. Feel free to close it.

**Comment by kathys** [comment]
This was just a mistake on my part.  I used the `-–weight-distance-max` of 1 in the Version 2.3 version of the doc, and I was letting it default to using a value of 2 in my example above.  Once I added this option to my execution, the resolution is identical to previous versions.
