### ISSUE TITLE
Version of Geo2Grid that processes GOES-18 imagery properly?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#567]
Greetings.   We are wondering if there are plans to release an updated release version of Geo2Grid before the prospective date (04Jan2023) when GOES-18 is slated to replace GOES-17 as the operational GOES-West satellite?  The reason this is important is that currently, one has to use version  1.1.b.2  (geo2grid-swbundle-20220406-161921) to get the (beautiful)  true_color product to be generated.   Neither version 1.0.2 (the current release version, ) or 1.1.b (geo2grid-swbundle-20220308-201316) work properly.  If you want, I can provide output from the two (2) failed jobs.

Thank you!

Sincerely,

Jim

**Comment by djhoese** [comment]
The latest beta is mentioned on this forum post:

https://forums.ssec.wisc.edu/viewtopic.php?t=59596

Sorry, I thought you had been informed about that. But there is actually a newer one here:

https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20221025-182017.tar.gz

We hope to release Geo2Grid 1.1 officially in the next 20 days. I'm going to close this since it is already on our todo list, but feel free to continue commenting.

**Comment by jpnIII** [comment]
Thank you again, Dave – Very good!

FYI, the link found in the middle of    https://forums.ssec.wisc.edu/viewtopic.php?t=59596 ( https://bin.ssec.wisc.edu/pub/CSPP/geo2grid/geo2grid-swbundle-20220718-201315-beta2.gz ) says “Not Found”
Later.

Jim

**Comment by jpnIII** [comment]
I’m sorry, Dave –  I’m sure you told/emailed me about the new release, and I forgot or misplaced the mail.   ☹

But thank you – The plans sound great!

Happy Thanksgiving to you and yours.

Sincerely,

Jim

P.S.   https://forums.ssec.wisc.edu/viewtopic.php?t=59596  says “Not found”
