### ISSUE TITLE
Order of Products with --list-products and --list-products-all

### ISSUE THREAD

**Issue by ScottLindstrom** [ssec/polar2grid#572]
--list-products will output ### Custom User Products and then ### Standard Available Geo2Grid Products.
--list-products will output ### Custom User Products then ### Non-standard Satpy Products and then ### Standard Available Geo2Grid Products.

Can the order be changed so that ### Custom User Products is listed  last rather than first?  That ends up at the bottom of the listing and is easier to see for a user.

**Comment by kathys** [comment]
I am not sure that I agree with you @ScottLindstrom.  I think the most important thing is to be consistent, so that users get used to looking for it in the right place.  I am hesitant to change anything at this point unless there is a bug.

**Comment by djhoese** [comment]
I agree with everyone :wink: sort of.

* I agree with Kathy that we don't want to change anything in G2G v1.1 now.
* I agree with Scott that in `--list-products-all` I, as a user, would expect to see my custom products last and closest to my next prompt. I'm not sure it makes as much sense in `--list-products` since we may have "custom"/example composites that are built in like `true_color_night` that the user will always see. Users who don't want to make a custom composite will be confused why that is shown and isn't a default product and somehow has more importance than the "builtin" ones. If it wasn't for this confusion I would agree that they should be last.
* I agree with Kathy that the two flags (`--list-products` and `--list-products-all`) should be consistent in the order they show products.

**Comment by kathys** [comment]
Decided we are going to leave the way it is.

**Comment by ScottLindstrom** [comment]
[like]  Scott Lindstrom reacted to your message:
________________________________
